name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Eksekusi hanya saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /repositories/Furion-Gym-Jambi-V2/ # Sesuaikan folder di cPanel
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            .env